In [1]:
import torch
#import torch_geometric

# Define Graph
# Store in torch representation

edge_list = torch.tensor([
[0, 0, 0, 1, 2, 2, 3], # Source nodes
[1, 2, 3, 0, 0, 2, 0] # Target Nodes
], dtype=torch.long)

In [2]:
edge_list

tensor([[0, 0, 0, 1, 2, 2, 3],
        [1, 2, 3, 0, 0, 2, 0]])

In [ ]:
import torch_geometric.data

In [ ]:
import torch_scatter

In [ ]:
import torch_scatter

In [3]:
# 6 Features for each node :: 4 x 6 representation

node_features = torch.tensor([
    [-0, 1, 5, 0, 2, 3], # Features node 0
    [-1, 0, 2, -3, 0, 1], # Features node 1
    [1, -1, 0, -1, 2, 1], # Features node 2
    [0, 1, 4, -2, 3, 4] # Features node 3
], dtype=torch.long)

In [6]:
node_features

tensor([[ 0,  1,  5,  0,  2,  3],
        [-1,  0,  2, -3,  0,  1],
        [ 1, -1,  0, -1,  2,  1],
        [ 0,  1,  4, -2,  3,  4]])

In [4]:
torch.__version__

'1.12.1'

In [2]:
torch.jit._state.disable()

In [ ]:
from torch_geometric.nn import Sequential, GCNConv

In [7]:
edge_list.T

tensor([[0, 1],
        [0, 2],
        [0, 3],
        [1, 0],
        [2, 0],
        [2, 2],
        [3, 0]])

In [8]:
edge_weight = torch.tensor([
    [35.], # Weights for nodes (0-1)
    [48.], # Weights for nodes (0-2)
    [12.], # Weights for nodes (0-3)
    [70.], # Weights for nodes (1,0)
    [5.], # Weights for nodes (2,0)
    [15.], # Weights for nodes (2,2)
    [8.], # Weights for nodes (3,0)
], dtype=torch.long)

/var/folders/gw/lkyxjfl92n9_j9h7mdgfz55c0000gq/T/ipykernel_37332/179236310.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  edge_weight = torch.tensor([


In [9]:
edge_weight

tensor([[35],
        [48],
        [12],
        [70],
        [ 5],
        [15],
        [ 8]])